export const GET_CART_PRODUCT = "CART::GET_CART_PRODUCT";
export const SET_CART_PRODUCT = "CART::SET_CART_PRODUCT";
export const DELETE_CART_PRODUCT_ITEM = "CART::DELETE_CART_PRODUCT_ITEM";
export const DELETE_CART_PRODUCT_ITEM_ID = "CART::DELETE_CART_PRODUCT_ITEM_ID";
export const RESET_DATA = "CART::RESET_DATA";
