export const UPDATE_CURRENT_PAGE = "PRODUCT::UPDATE_CURRENT_PAGE";
export const SET_PRODUCT_ITEM = "PRODUCT::SET_PRODUCT_ITEM";
export const RESET_PRODUCT_ITEM = "PRODUCT::RESET_PRODUCT_ITEM";
export const SET_FILTER_ITEM = "PRODUCT::SET_FILTER_ITEM";
export const RESET_FILTERS = "PRODUCT::RESET_FILTERS";
